---
- name: Create Stacey configuration for Nginx
  template: src="stacey-site.conf.j2"
            dest="/etc/nginx/sites-available/{{ item.key }}.conf"
  with_dict: sites
  notify: reload nginx

- name: Enable Stacey site
  file: src="/etc/nginx/sites-available/{{ item.key }}.conf"
        dest="/etc/nginx/sites-enabled/{{ item.key }}.conf"
        owner=root
        group=root
        state=link
  with_dict: sites
  notify: reload nginx
