---
- include: directories.yml

- name: Create .env file
  template: src="env.j2"
            dest="{{ www_root }}/{{ item.key }}/current/.env"
            owner="{{ web_user }}"
            group="{{ web_group }}"
  with_dict: sites

- name: Restart HHVM
  service: name=hhvm state=restarted
  when: hhvm | default(False)
