---
- name: "Stacey Server: Install PHP 5.6 and Dropbox"
  hosts: web
  sudo: yes
  remote_user: vagrant

  roles:
    - { role: common, tags: [common] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp }
    - { role: ssmtp, tags: [ssmtp mail] }
    - { role: php, when: not hhvm, tags: [php] }
    - { role: hhvm, when: hhvm, tags: [hhvm] }
    - { role: php5-xdebug, tags: [xdebug], when: xdebug_install | default(False) }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: dropbox, tags: [dropbox] }
