---
- name: "Stacey Server: Install PHP 5.6 and Dropbox"
  hosts: web
  remote_user: root

  roles:
    - { role: common, tags: [common] }
    - { role: swapfile, swapfile_size: 1GB, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp }
    - { role: users, tags: [users] }
    - { role: php, when: not hhvm, tags: [php] }
    - { role: hhvm, when: hhvm, tags: [hhvm] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: memcached, tags: [memcached] }
    - { role: composer, tags: [composer] }
    - { role: dropbox, tags: [dropbox] }
    - { role: github-ssh-keys, tags: [github-ssh-keys], when: github_ssh_keys is defined }
