---
- name: Add MariaDB MySQL apt-key
  apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search={{ keyserver_fingerprint }}"
           state=present

- name: Add MariaDB MySQL deb and deb-src
  apt_repository: repo="{{ item }}" state=present
  with_items:
  - "deb http://{{ mirror }}/mariadb/repo/{{ version }}/ubuntu {{ mariadb_dist | default(ansible_distribution_release) }} main"
  - "deb-src http://{{ mirror }}/mariadb/repo/{{ version }}/ubuntu {{ mariadb_dist | default(ansible_distribution_release) }} main"

- name: Install MariaDB MySQL server
  apt: name=mariadb-server state=present

- name: Start MariaDB MySQL Server
  service: name=mysql state=started enabled=true

- name: Set root user password
  mysql_user: name=root
              host="{{ item }}"
              password="{{ mysql_root_password }}"
              check_implicit_admin=yes
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
              state=present
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Delete anonymous MySQL server users
  mysql_user: user=""
              host="{{ item }}"
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
              state=absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db: name=test
            state=absent
            login_user="{{ mysql_user }}"
            login_password="{{ mysql_root_password }}"
